# 21/12/2025 Chembl validation pipeline Bin Chen LINCS data only

In [1]:
import os
if not os.getcwd().endswith('src'):
    os.chdir('../src')

# this works with conf file created on 18/11 related to chembl validation:
from conf import BASE_DIR, TSR_OUT_DRUG, cell_line, pert_time, DISEASE, MITH_IN_DISEASE, MITH_IN_DRUG, map_name_to_id, MITH_APP, MITH_OUT_DRUG, MITH_OUT_DISEASE,\
CS_IN_DRUG, CS_IN_DISEASE, cell_lines_chembl, diseases_of, DATA_DIR, CS_DIR

from validations.chembl.chembl_loader import load_raw_chembl
import numpy as np
from preprocessing_utils import get_drugs_list
import pandas as pd
import pyreadr
import subprocess
from step3_mith_out_to_cs_in_disease import mith_to_cs_in,write_cs_input
from step6_drug_run_MITHrIL import run_mithril_batch


print(cell_line, pert_time, DISEASE)

HEPG2 6h LIHC

# Run MIthril on Bin Chen TCGA data

### create Mithril input from TCGA fodl cahnge data

In [30]:
from conf import DATA_DIR

DATA_DIR
tcga = pd.read_excel(DATA_DIR+'BinChen2017'+os.sep+'SD2.xlsx', sheet_name = DISEASE+'_sig.csv')
tcga

C:\Users\los4\miniconda3\envs\drug_repurposing\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Unnamed: 0,id,baseMean,baseMeanA,baseMeanB,foldChange,log2FoldChange,pval,padj,symbol,GeneID,landmark
0,?|155060,?|155060,246.542053,63.387397,271.093615,4.276775,2.096523,2.322021e-11,4.919731e-10,?,155060,NaN
1,?|653553,?|653553,980.160561,308.154958,1070.241741,3.473064,1.796209,8.513384e-06,7.002229e-05,?,653553,NaN
2,AADAT|51166,AADAT|51166,539.906063,2260.466429,309.267944,0.136816,-2.869691,1.150033e-66,1.149267e-63,AADAT,51166,NaN
3,ABAT|18,ABAT|18,14667.875458,36469.512297,11745.404032,0.322061,-1.634595,1.161602e-36,3.214599e-34,ABAT,18,NaN
4,ABCA8|10351,ABCA8|10351,1142.503781,2728.212260,929.942323,0.340861,-1.552743,4.159067e-18,1.928178e-16,ABCA8,10351,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1187,ZNF695|57116,ZNF695|57116,18.119918,0.749038,20.448455,27.299608,4.770808,9.450933e-05,5.933800e-04,ZNF695,57116,NaN
1188,ZNF716|441234,ZNF716|441234,12.960449,0.068870,14.688543,213.279970,7.736605,1.291987e-05,1.016635e-04,ZNF716,441234,NaN
1189,ZNF883|169834,ZNF883|169834,41.344740,6.280339,46.045062,7.331620,2.874132,3.883273e-05,2.714820e-04,ZNF883,169834,NaN
1190,ZSWIM5|57643,ZSWIM5|57643,278.072279,76.284806,305.121538,3.999768,1.999916,2.617952e-10,4.834879e-09,ZSWIM5,57643,NaN
1191,ZWINT|11130,ZWINT|11130,631.934077,114.153249,701.341695,6.143861,2.619146,7.559177e-26,6.764900e-24,ZWINT,11130,NaN

In [29]:
tcga[tcga.id=="ADRB2|154"]

Empty DataFrame
Columns: [Unnamed: 0, id, baseMean, baseMeanA, baseMeanB, foldChange, log2FoldChange, pval, padj, symbol, GeneID, landmark]
Index: []

In [31]:
tcga.id.to_csv('SD2_LIHC.txt')

In [32]:
os.getcwd()

'G:\\My Drive\\unict\\unict 2024-25\\netcos\\src'

In [25]:
len(.unique())

1192

In [34]:
print('TODO save landmark ONLY')

TODO save landmark ONLY

In [3]:
fc=tcga[['id','log2FoldChange']]
def split_id(id_line):
    return id_line.split('|')[1]
fc['id']=fc['id'].apply(lambda x : split_id(x))
fc.set_index('id', inplace=True)
fc

C:\Users\los4\AppData\Local\Temp\ipykernel_18400\2076856619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fc['id']=fc['id'].apply(lambda x : split_id(x))

        log2FoldChange
id
344752       -6.451391
10349        -1.535628
26154         5.191762
23460        -2.654010
10351        -4.637989
...                ...
57116         2.297532
84133         1.699489
7784          1.511082
65249         1.565816
23140        -1.780432

[2054 rows x 1 columns]

In [4]:
#export as mitrhil input
from conf import MITH_IN_DISEASE
fc.to_csv(MITH_IN_DISEASE+DISEASE+'_signature_gene_id.mi', header=None, sep='\t')

In [8]:
from step2_disease_run_MITHrIL import run_mithril, MITH_OUT_DISEASE

In [52]:
run_mithril(DISEASE, MITH_APP, MITH_IN_DISEASE, MITH_OUT_DISEASE)

java -jar /home/signorini/mithril3/app-3.0.0-SNAPSHOT.jar mithril -reactome -p -customize-pathway-matrix -seed 1234 -inversion-factory fast-cpu -multiplication-factory fast-cpu -t 30 -i G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\input\disease_signature\LIHC_signature_gene_id.mi -organism hsa_v2023_03 -o G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\output\disease_signature_2025\LIHC_mith3.output.txt -p G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\output\disease_signature_2025\LIHC_mith3.perturbations.txt -verbose

# Run MITHrIL on bin chen LINCS data for HEPG2

## Get Bin Chen Drug Fold Change data

In [ ]:
i fold change sono dentro
data/lincs/lincs_signatures_cmpd_landmark.Rdata' chee' una matrice 978xcirca66k dove 978 sono i landmark genes e 66k 
sono i profili da [[binchen2015 suppl]]. 
gli altri files dentro lincs e negli altri sono i metadati su cui mappare lincs. per filtrare solamente le drugs testate
nell cell lines che vogliamo. Bienone.
famo sto filtraggio e vediamo se equanto corrisponde.

In [2]:
Bin_chen_lincs_data_dir=DATA_DIR+'BinChen2017'+os.sep+'data'+os.sep+'data'+os.sep+'raw'+os.sep+'lincs'+os.sep
result = pyreadr.read_r(Bin_chen_lincs_data_dir+'lincs_signatures_cmpd_landmark.RData') # also works for Rds

print(result.keys()) # let's check what objects we got
LINCS_signatures = result["lincs_signatures"]

odict_keys(['lincs_signatures'])

In [3]:
LINCS_signatures

,155341,155393,155435,155493,155500,155530,155541,155556,155589,155613,...,454026,454033,454034,454036,454037,454038,454039,454041,454042,454045
5720,0.3447,-0.0990,0.6015,-0.8181,1.2216,-0.9643,-1.5340,-1.6395,-1.2776,-1.1108,...,1.6284,1.3197,0.4599,0.9842,1.7562,1.5712,1.3897,-0.4815,-0.1226,-0.5701
466,0.4032,-0.5594,0.0691,-0.2245,-1.0532,0.2322,-0.2734,-0.1022,-0.4128,-1.0570,...,-4.3028,-2.7984,-2.6535,-4.5854,-4.4473,-2.1747,-0.2854,-1.2048,-1.4508,-0.3068
6009,1.0289,-1.0509,0.5279,-1.5210,-0.9870,-0.6199,-0.3704,-0.7890,-1.3335,-0.4627,...,-1.3570,-1.3942,-1.1194,-1.0236,-0.2892,0.0817,0.0324,0.7010,0.4210,0.3240
2309,0.3677,-2.3432,0.0676,1.2043,-0.7199,-0.4049,-0.1203,-1.0923,0.1178,1.6167,...,1.2244,1.4860,1.2601,1.1203,1.6074,0.8959,-0.6045,1.6354,1.4549,2.1727
387,2.0567,-0.5860,0.5985,0.3303,-0.5947,-1.7296,0.0984,-0.9721,-1.3875,0.2876,...,0.0244,0.1747,-0.4152,0.0714,0.3855,0.8818,0.2577,-0.4625,-0.2828,-1.6440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23200,1.5430,1.1971,-0.3594,0.8270,0.5941,0.9918,-3.2082,1.6730,0.5038,-1.3893,...,-0.1590,-1.2681,-0.5173,0.0528,-0.3743,1.1204,1.0565,0.0037,-0.6502,0.8897
51293,-0.1638,-1.3276,1.9958,0.8311,-0.4724,-0.2969,0.5911,-0.2883,-0.0932,0.0248,...,0.2969,-2.4767,-1.0687,-0.9357,-1.8297,-2.0583,-0.5919,-0.2968,-0.6812,0.3399
10962,0.0792,-2.1704,-0.4622,-1.1528,-0.7197,-0.9370,-0.6370,-1.7314,-0.0596,-0.6252,...,0.4808,0.2260,1.8578,-0.2791,1.7424,3.6395,3.5416,-1.1799,-0.2770,-0.6461
10153,0.0692,1.4227,-0.7396,0.7512,-0.2070,-0.2230,-1.9660,-0.1912,-0.0285,1.0721,...,0.3468,1.3060,-0.2166,1.7471,0.4430,0.3161,0.1687,-0.5178,-0.7392,0.0231
874,0.8137,-1.7838,0.6401,-0.1486,1.2253,-0.2523,-0.5332,0.3021,-0.1682,-0.6282,...,-4.9468,-3.8730,-1.6843,-4.8996,-5.5928,-0.7667,1.0116,0.5691,0.5409,1.1657

In [4]:
# load metadata about perturbagen and drug
metadata=pd.read_csv(Bin_chen_lincs_data_dir+'lincs_sig_info.csv')
metadata2=pd.read_csv(Bin_chen_lincs_data_dir+'lincs_sig_info_new.csv') #to check for diff later

In [5]:
metadata

,id,sig_id,pert_id,pert_iname,pert_desc,cell_id,pert_time,pert_dose,pert_type,is_gold,DrugBank.ID
0,0,CPC006_A673_6H:BRD-K81473043-001-04-7:0.35,BRD-K81473043,tanespimycin,-666,A673,6,0.35,trt_cp,1,NaN
1,1,CPC005_A375_6H:BRD-A07824748-001-02-6:10,BRD-A07824748,flavanone,-666,A375,6,10.00,trt_cp,1,NaN
2,5,CPC004_A375_6H:BRD-K03670461-001-02-0:10,BRD-K03670461,tyrphostin-AG-82,AG 82,A375,6,10.00,trt_cp,1,NaN
3,6,CPC004_A375_6H:BRD-K36737713-001-01-6:10,BRD-K36737713,AG-957,AG 957,A375,6,10.00,trt_cp,1,NaN
4,8,CPC004_A375_6H:BRD-A14966924-001-03-0:10,BRD-A14966924,alaproclate,ALAPROCLATE,A375,6,10.00,trt_cp,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
66506,454038,ERG015_VCAP_6H:BRD-K81418486-001-15-2:0.4,BRD-K81418486,vorinostat,vorinostat,VCAP,6,0.40,trt_cp,1,DB02546
66507,454039,ERG015_VCAP_6H:BRD-K81418486-001-15-2:0.08,BRD-K81418486,vorinostat,vorinostat,VCAP,6,0.08,trt_cp,1,DB02546
66508,454041,ERG014_VCAP_6H:BRD-A75409952-001-01-6:10,BRD-A75409952,wortmannin,wortmannin,VCAP,6,10.00,trt_cp,1,NaN
66509,454042,ERG014_VCAP_6H:BRD-A75409952-001-01-6:2,BRD-A75409952,wortmannin,wortmannin,VCAP,6,2.00,trt_cp,1,NaN
66510,454045,ERG015_VCAP_6H:BRD-A75409952-001-01-6:10,BRD-A75409952,wortmannin,wortmannin,VCAP,6,10.00,trt_cp,1,NaN

In [6]:
# Filter for is_gold=1 Bin CHen 2015 suppl: small molecular perturbagens with high quality gene expression profiles

In [7]:
list_of_perturbations = [str(x) for x in metadata["id"][metadata["is_gold"]==1] if str(x) in LINCS_signatures.columns] #ma qst e' na matrice. Mi va bene cosi? avro molte drugs e molte cose per cell line penso?
LINCS_signatures =  LINCS_signatures[list_of_perturbations]
LINCS_signatures

,1,5,6,8,9,14,16,19,20,29,...,454026,454033,454034,454036,454037,454038,454039,454041,454042,454045
5720,-0.6456,-5.3887,-1.0002,0.0633,0.5609,-0.2354,-4.7976,-1.3678,-0.1924,-2.1586,...,1.6284,1.3197,0.4599,0.9842,1.7562,1.5712,1.3897,-0.4815,-0.1226,-0.5701
466,-0.8107,1.8677,-1.1061,-0.9626,-0.6567,-0.3239,3.5131,0.1095,-0.0914,2.4530,...,-4.3028,-2.7984,-2.6535,-4.5854,-4.4473,-2.1747,-0.2854,-1.2048,-1.4508,-0.3068
6009,0.4591,0.2814,-0.4225,0.5216,0.5203,-0.0719,-1.7471,-0.8510,-2.2318,-2.0554,...,-1.3570,-1.3942,-1.1194,-1.0236,-0.2892,0.0817,0.0324,0.7010,0.4210,0.3240
2309,-0.2247,1.3782,0.4063,0.1824,-0.3157,-0.4211,2.9504,0.2852,0.8032,4.4114,...,1.2244,1.4860,1.2601,1.1203,1.6074,0.8959,-0.6045,1.6354,1.4549,2.1727
387,-0.3357,1.2905,-0.2187,0.5722,-0.1879,-0.2777,3.1947,0.2627,-0.0314,-0.5671,...,0.0244,0.1747,-0.4152,0.0714,0.3855,0.8818,0.2577,-0.4625,-0.2828,-1.6440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23200,0.9083,-0.2669,0.5190,0.2252,0.4136,-0.1006,-1.6706,0.2632,-0.1269,-0.9955,...,-0.1590,-1.2681,-0.5173,0.0528,-0.3743,1.1204,1.0565,0.0037,-0.6502,0.8897
51293,-2.1830,-1.4307,-0.1090,-1.6135,-0.2662,-0.1641,-4.8412,-0.1617,1.0503,-1.0851,...,0.2969,-2.4767,-1.0687,-0.9357,-1.8297,-2.0583,-0.5919,-0.2968,-0.6812,0.3399
10962,-1.5938,-1.4906,1.5167,-0.5391,-0.8986,0.0210,-2.1250,0.9805,-0.1916,2.5892,...,0.4808,0.2260,1.8578,-0.2791,1.7424,3.6395,3.5416,-1.1799,-0.2770,-0.6461
10153,-0.2009,-1.9033,0.4269,-3.0805,-0.0043,0.2500,-1.4175,0.6213,0.0625,-3.4827,...,0.3468,1.3060,-0.2166,1.7471,0.4430,0.3161,0.1687,-0.5178,-0.7392,0.0231
874,-1.9850,-3.8466,0.7865,-0.7273,-0.2472,-0.0210,-0.2906,-0.4574,0.2505,-2.6283,...,-4.9468,-3.8730,-1.6843,-4.8996,-5.5928,-0.7667,1.0116,0.5691,0.5409,1.1657

In [8]:
# select only drugs for given selected cell line:\
# this cell line is the one that was selected to compare with IC50 because of the amount of common compounds

In [9]:
list_of_perturbations = [str(x) for x in metadata["id"][metadata["cell_id"]==cell_line]] #ma qst e' na matrice. Mi va bene cosi? avro molte drugs e molte cose per cell line penso?
subset_fc =  LINCS_signatures[list_of_perturbations]
print(len(list_of_perturbations), subset_fc.shape)

2418 (978, 2418)

In [10]:
# da vedere: cos'e' sta roba? 2418 esperimenti per sta cellula, me li pappo tutti?

In [11]:
# print drugs
subset_metadata = metadata[metadata["cell_id"]==cell_line]
grouped = subset_metadata.groupby("pert_iname")

grouped.count()

,id,sig_id,pert_id,pert_desc,cell_id,pert_time,pert_dose,pert_type,is_gold,DrugBank.ID
pert_iname,,,,,,,,,,
"1,2-dichlorobenzene",1,1,1,1,1,1,1,1,1,0
1-benzylimidazole,1,1,1,1,1,1,1,1,1,1
1-phenylbiguanide,1,1,1,1,1,1,1,1,1,0
10-DEBC,1,1,1,1,1,1,1,1,1,0
15-delta-prostaglandin-j2,2,2,2,2,2,2,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...
zileuton,1,1,1,1,1,1,1,1,1,1
ziprasidone,1,1,1,1,1,1,1,1,1,1
zolantidine,1,1,1,1,1,1,1,1,1,0
zoxazolamine,1,1,1,1,1,1,1,1,1,0
zuclopenthixol,1,1,1,1,1,1,1,1,1,1

In [12]:
grouped = subset_metadata.groupby("is_gold")
grouped.count()

,id,sig_id,pert_id,pert_iname,pert_desc,cell_id,pert_time,pert_dose,pert_type,DrugBank.ID
is_gold,,,,,,,,,,
1,2418,2418,2418,2418,2418,2418,2418,2418,2418,352

In [13]:
grouped = subset_metadata.groupby("pert_dose")
grouped.count()

,id,sig_id,pert_id,pert_iname,pert_desc,cell_id,pert_time,pert_type,is_gold,DrugBank.ID
pert_dose,,,,,,,,,,
0.0400,1,1,1,1,1,1,1,1,1,1
0.0800,4,4,4,4,4,4,4,4,4,2
0.0900,2,2,2,2,2,2,2,2,2,0
0.1563,2,2,2,2,2,2,2,2,2,0
0.1600,8,8,8,8,8,8,8,8,8,0
...,...,...,...,...,...,...,...,...,...,...
111.1100,1,1,1,1,1,1,1,1,1,0
120.0000,1,1,1,1,1,1,1,1,1,0
122.5500,1,1,1,1,1,1,1,1,1,0
160.0000,9,9,9,9,9,9,9,9,9,2
177.6000,3,3,3,3,3,3,3,3,3,2

## Convert FC to MITHrIL input for given drug

In [7]:
# TO RUN FOR ALL INSTANCES
for cell_line in cell_lines:
    for pert_time in pert_times:

        # code from validations/chembl/tsr_out_to_mith_in.py
        DRUG_DIR = TSR_OUT_DRUG+'LINCS'+os.sep+cell_line+'_'+pert_time+'_drug_wise'+os.sep
        df_list=[]
        for i, drug_file in enumerate(os.listdir(DRUG_DIR)):
            drug = drug_file.rstrip('.Rds')
            try:
                result = pyreadr.read_r(DRUG_DIR+drug_file)
                df = result[None] 
                df.set_index('gene_id', inplace=True)
                df.rename(columns = {'DE_log2_FC':drug}, inplace = True)
                
                df_list.append(df[drug])
            except:
                print('.Rds reading error for:', drug_file)
        
        matrix=pd.concat(df_list, axis=1)
        print(matrix.shape)
        print(matrix.columns)
        print(matrix.head(3))
        
        # Save MITHrIL gene id based input file:
        mith_input_filename = 'LINCS_'+cell_line+'_'+pert_time+'.mi'
        matrix.to_csv(MITH_IN_DRUG+mith_input_filename, sep='\t', index=True,  index_label=False)
        print('MITHrIL drug input saved in',MITH_IN_DRUG,'filename:',mith_input_filename)

isonicotinohydroxamic-aci
tozasertib
clomifene
tamoxifen
BRD-A08658758
avrainvillamide-analog-3
vinblastine
IKK-2-inhibitor-V
MW-SHH-54
NSC-632839
MW-SHH-97
BRD-K00640357
diethylstilbestrol
bucladesine
alpha-estradiol
avrainvillamide-analog-1
trichostatin-a
sulforaphane
SIB-1893
equol
estradiol
pentamidine
KI-8751
COL-3
BRD-K75627148
BRD-K67774729
avrainvillamide-analog-4
BRD-K52160314
tyrphostin-AG-879
BRD-K35832492
tert-butylhydroquinone
hydroxyl
HDAC1-selective
podophyllotoxin
staurosporine
AT-9283
simvastatin
BRD-K57064803
malonoben
BRD-K98948170
BRD-K83694683
BRD-K16956545
CGP-53353
KUC111109N
niacin
avrainvillamide-analog-6
A-23187
apicidin
KUC111774N
AT1-SHH-09
crizotinib
BRD-K55896799
BRD-K64106162
tyrphostin-A9
BRD-K61894884
atorvastatin
BRD-K11533227
barasertib-HQPA
estrone
FL-HDAC-025
doxorubicin
arctigenin
avicin-
fulvestrant
BRD-K99636700
raloxifene
benzohydroxamic-aci
MK-5108
spiramide
BRD-K22587354
erastin
sirolimu
Ro-90-7501
pifithrin-mu
BRD-K58547375
BRD-K21001652
ENMD-2076
ZK-93423
phorbol-myristate-acetate
NSC-95397
BRD-K01737880
curcumin
tigecycline
WY-01-034
D-64131
CGS-15943
spiperone
BRD-K60932973
BRD-K64024097
MW-SHH-28
equilin
estriol
BRD-K19826688
panobinostat
nilotinib
TL-HRAS-61
MW-SHH-151
cyclopentene
ZM-447439
tacedinaline
ellipticine
BRD-K19876534
cycloheximide
alisertib
CGK-733
BRD-K56411643
mitoxantrone
homoharringtonine
ichthynone
entinostat
tyrphostin-AG-527
toremifene
BRD-K26510616
emetine
genistein
STK-721917
BRD-K54343811
BRD-K10436544
BRD-K22321414
AVA
MW-SHH-61
SJB-shh-31
BRD-K59019422
dropropizine
BL003-049-HDAC3
cilostamide
wortmannin
tubastatin-a
BRD-K16410418
MW-SHH-250
trequinsin
BRD-K93367411
geldanamycin
mycophenolic-aci
BRD-K35860134
vorinostat
oxaprozin
BRD-K89097220
MW-SHH-98
WY-01-045
PF-543
PCI-34051
AT1-SHH-29
cucurbitacin-i
BRD-K01621458
FCCP
BRD-K83493571
BRD-A36275421
HDAC3-selective
dienestrol
BRD-K82092559
BRD-K91338578
BRD-K55533488
LY-2183240
(10174, 154)
Index(['isonicotinohydroxamic-aci', 'tozasertib', 'clomifene', 'tamoxifen',
       'BRD-A08658758', 'avrainvillamide-analog-3', 'vinblastine',
       'IKK-2-inhibitor-V', 'MW-SHH-54', 'NSC-632839',
       ...
       'BRD-K01621458', 'FCCP', 'BRD-K83493571', 'BRD-A36275421',
       'HDAC3-selective', 'dienestrol', 'BRD-K82092559', 'BRD-K91338578',
       'BRD-K55533488', 'LY-2183240'],
      dtype='object', length=154)
         isonicotinohydroxamic-aci  tozasertib  clomifene  tamoxifen  \
gene_id
780                      -0.434621   -0.132363  -0.420229  -0.559186
7849                     -0.452756   -0.676705  -0.274957  -0.418547
2049                      0.218476    0.120122   0.343729   0.077321

         BRD-A08658758  avrainvillamide-analog-3  vinblastine  \
gene_id
780          -0.680446                  0.049614     0.272638
7849         -0.219888                 -0.463758    -0.778414
2049          0.506922                 -0.321766     0.127879

         IKK-2-inhibitor-V  MW-SHH-54  NSC-632839  ...  BRD-K01621458  \
gene_id                                            ...
780               0.978171   0.039130   -0.693696  ...      -0.631963
7849             -1.726414  -0.132170   -2.497181  ...      -0.401671
2049             -0.405355  -0.060547    0.892662  ...       0.096322

             FCCP  BRD-K83493571  BRD-A36275421  HDAC3-selective  dienestrol  \
gene_id
780      1.363554      -0.719520      -1.033451        -0.185797   -0.184919
7849    -1.568097       1.322293      -0.255807        -0.454571   -0.230117
2049    -0.212188      -0.565838       2.643177         0.313972   -0.718541

         BRD-K82092559  BRD-K91338578  BRD-K55533488  LY-2183240
gene_id
780           0.579838      -0.070903      -0.108647   -0.140429
7849          0.462376      -0.340026      -0.161672   -1.018764
2049          0.033912       0.217437      -0.315545   -0.366388

[3 rows x 154 columns]

MITHrIL drug input saved in G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\input\drug_signature\ filename: LINCS_HEPG2_24h.mi

## <b>MITHrIL batch run</b>

In [5]:
from conf import mith_threads, mith_organism
print(mith_threads, mith_organism)

10 hsa

In [27]:
mith_input_filename=mith_input_filename
mith_input_file = 'LINCS_'+cell_line+'_'+pert_time+'.mi'
run_mithril_batch(mith_input_filename, MITH_APP, MITH_IN_DRUG, MITH_OUT_DRUG, n_thread=mith_threads, organism=mith_organism, printc=True)

java -jar /home/signorini/mithril3/app-3.0.0-SNAPSHOT.jar mithril-batch -reactome -p -customize-pathway-matrix -seed 1234 -inversion-factory fast-cpu -multiplication-factory fast-cpu -t 2 -organism hsa -i G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\input\drug_signature\LINCS_HEPG2_24h.mi -o G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\output\drug_signature_2025_HEPG2_24h\ -p -verbose

# Calculate CS for given TCGA disease and realtive LINCS cell line PF

In [2]:
from step7_drug_mith_out_to_cs_in import mith_out_to_cs_in_single_time, CS_IN_DRUG

print(cell_line, pert_time, DISEASE)
print(MITH_OUT_DRUG)
print(CS_IN_DRUG)

MCF7 24h temp
G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\output\drug_signature_2025\MCF7_24h\
G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\output\disease_signature_2025\
G:\My Drive\unict\unict 2024-25\netcos\connectivity_score\input\drug_signature_2025\MCF7_24h\

## convert drug mith output into cs input

In [3]:
drugs_list=get_drugs_list(True)
print(len(drugs_list))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\My Drive\\unict\\unict 2024-25\\netcos\\MITHrIL\\output\\drug_signature_2025\\MCF7_24h\\'

In [3]:
mith_out_to_cs_in_single_time(drugs_list, pert_time)

Mapping mith3 output into tsr connectivity input:
              Removing pathway duplicates, and filtering
A-23187 1 of 68
drug A-23187 processed in 0.8
writing mit3 connectivity input metanalysis files for drug A-23187
AT1-SHH-09 2 of 68
drug AT1-SHH-09 processed in 0.8
writing mit3 connectivity input metanalysis files for drug AT1-SHH-09
AVA 3 of 68
drug AVA processed in 0.7
writing mit3 connectivity input metanalysis files for drug AVA
BL003-049-HDAC3 4 of 68
drug BL003-049-HDAC3 processed in 0.7
writing mit3 connectivity input metanalysis files for drug BL003-049-HDAC3
BRD-A08658758 5 of 68
drug BRD-A08658758 processed in 0.9
writing mit3 connectivity input metanalysis files for drug BRD-A08658758
BRD-K00640357 6 of 68
drug BRD-K00640357 processed in 0.7
writing mit3 connectivity input metanalysis files for drug BRD-K00640357
BRD-K11533227 7 of 68
drug BRD-K11533227 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K11533227
BRD-K16410418 8 of 68
drug BRD-K16410418 processed in 0.7
writing mit3 connectivity input metanalysis files for drug BRD-K16410418
BRD-K16956545 9 of 68
drug BRD-K16956545 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K16956545
BRD-K19826688 10 of 68
drug BRD-K19826688 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K19826688
BRD-K19876534 11 of 68
drug BRD-K19876534 processed in 0.9
writing mit3 connectivity input metanalysis files for drug BRD-K19876534
BRD-K35832492 12 of 68
drug BRD-K35832492 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K35832492
BRD-K54343811 13 of 68
drug BRD-K54343811 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K54343811
BRD-K56411643 14 of 68
drug BRD-K56411643 processed in 0.7
writing mit3 connectivity input metanalysis files for drug BRD-K56411643
BRD-K59019422 15 of 68
drug BRD-K59019422 processed in 0.7
writing mit3 connectivity input metanalysis files for drug BRD-K59019422
BRD-K61894884 16 of 68
drug BRD-K61894884 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K61894884
BRD-K64024097 17 of 68
drug BRD-K64024097 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K64024097
BRD-K67774729 18 of 68
drug BRD-K67774729 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K67774729
BRD-K75627148 19 of 68
drug BRD-K75627148 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K75627148
BRD-K89097220 20 of 68
drug BRD-K89097220 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K89097220
BRD-K93367411 21 of 68
drug BRD-K93367411 processed in 0.9
writing mit3 connectivity input metanalysis files for drug BRD-K93367411
BRD-K98948170 22 of 68
drug BRD-K98948170 processed in 0.8
writing mit3 connectivity input metanalysis files for drug BRD-K98948170
CGK-733 23 of 68
drug CGK-733 processed in 0.7
writing mit3 connectivity input metanalysis files for drug CGK-733
COL-3 24 of 68
drug COL-3 processed in 0.8
writing mit3 connectivity input metanalysis files for drug COL-3
ENMD-2076 25 of 68
drug ENMD-2076 processed in 0.7
writing mit3 connectivity input metanalysis files for drug ENMD-2076
FCCP 26 of 68
drug FCCP processed in 0.8
writing mit3 connectivity input metanalysis files for drug FCCP
FL-HDAC-025 27 of 68
drug FL-HDAC-025 processed in 0.8
writing mit3 connectivity input metanalysis files for drug FL-HDAC-025
LY-2183240 28 of 68
drug LY-2183240 processed in 0.7
writing mit3 connectivity input metanalysis files for drug LY-2183240
MK-5108 29 of 68
drug MK-5108 processed in 0.7
writing mit3 connectivity input metanalysis files for drug MK-5108
MW-SHH-250 30 of 68
drug MW-SHH-250 processed in 0.7
writing mit3 connectivity input metanalysis files for drug MW-SHH-250
MW-SHH-54 31 of 68
drug MW-SHH-54 processed in 0.7
writing mit3 connectivity input metanalysis files for drug MW-SHH-54
NSC-95397 32 of 68
drug NSC-95397 processed in 0.7
writing mit3 connectivity input metanalysis files for drug NSC-95397
SIB-1893 33 of 68
drug SIB-1893 processed in 0.8
writing mit3 connectivity input metanalysis files for drug SIB-1893
SJB-shh-31 34 of 68
drug SJB-shh-31 processed in 0.7
writing mit3 connectivity input metanalysis files for drug SJB-shh-31
STK-721917 35 of 68
drug STK-721917 processed in 0.8
writing mit3 connectivity input metanalysis files for drug STK-721917
WY-01-034 36 of 68
drug WY-01-034 processed in 0.7
writing mit3 connectivity input metanalysis files for drug WY-01-034
WY-01-045 37 of 68
drug WY-01-045 processed in 0.7
writing mit3 connectivity input metanalysis files for drug WY-01-045
ZK-93423 38 of 68
drug ZK-93423 processed in 0.8
writing mit3 connectivity input metanalysis files for drug ZK-93423
ZM-447439 39 of 68
drug ZM-447439 processed in 0.7
writing mit3 connectivity input metanalysis files for drug ZM-447439
avicin- 40 of 68
drug avicin- processed in 0.7
writing mit3 connectivity input metanalysis files for drug avicin-
barasertib-HQPA 41 of 68
drug barasertib-HQPA processed in 0.7
writing mit3 connectivity input metanalysis files for drug barasertib-HQPA
benzohydroxamic-aci 42 of 68
drug benzohydroxamic-aci processed in 0.8
writing mit3 connectivity input metanalysis files for drug benzohydroxamic-aci
bucladesine 43 of 68
drug bucladesine processed in 0.7
writing mit3 connectivity input metanalysis files for drug bucladesine
clomifene 44 of 68
drug clomifene processed in 0.8
writing mit3 connectivity input metanalysis files for drug clomifene
crizotinib 45 of 68
drug crizotinib processed in 0.9
writing mit3 connectivity input metanalysis files for drug crizotinib
cyclopentene 46 of 68
drug cyclopentene processed in 0.8
writing mit3 connectivity input metanalysis files for drug cyclopentene
dienestrol 47 of 68
drug dienestrol processed in 0.7
writing mit3 connectivity input metanalysis files for drug dienestrol
diethylstilbestrol 48 of 68
drug diethylstilbestrol processed in 0.9
writing mit3 connectivity input metanalysis files for drug diethylstilbestrol
emetine 49 of 68
drug emetine processed in 0.9
writing mit3 connectivity input metanalysis files for drug emetine
estrone 50 of 68
drug estrone processed in 0.9
writing mit3 connectivity input metanalysis files for drug estrone
genistein 51 of 68
drug genistein processed in 0.8
writing mit3 connectivity input metanalysis files for drug genistein
hydroxyl 52 of 68
drug hydroxyl processed in 0.8
writing mit3 connectivity input metanalysis files for drug hydroxyl
mitoxantrone 53 of 68
drug mitoxantrone processed in 0.8
writing mit3 connectivity input metanalysis files for drug mitoxantrone
mycophenolic-aci 54 of 68
drug mycophenolic-aci processed in 0.8
writing mit3 connectivity input metanalysis files for drug mycophenolic-aci
niacin 55 of 68
drug niacin processed in 0.7
writing mit3 connectivity input metanalysis files for drug niacin
oxaprozin 56 of 68
drug oxaprozin processed in 0.7
writing mit3 connectivity input metanalysis files for drug oxaprozin
pentamidine 57 of 68
drug pentamidine processed in 0.7
writing mit3 connectivity input metanalysis files for drug pentamidine
pifithrin-mu 58 of 68
drug pifithrin-mu processed in 0.7
writing mit3 connectivity input metanalysis files for drug pifithrin-mu
podophyllotoxin 59 of 68
drug podophyllotoxin processed in 0.6
writing mit3 connectivity input metanalysis files for drug podophyllotoxin
raloxifene 60 of 68
drug raloxifene processed in 0.7
writing mit3 connectivity input metanalysis files for drug raloxifene
spiramide 61 of 68
drug spiramide processed in 0.7
writing mit3 connectivity input metanalysis files for drug spiramide
staurosporine 62 of 68
drug staurosporine processed in 0.7
writing mit3 connectivity input metanalysis files for drug staurosporine
sulforaphane 63 of 68
drug sulforaphane processed in 0.7
writing mit3 connectivity input metanalysis files for drug sulforaphane
tigecycline 64 of 68
drug tigecycline processed in 0.8
writing mit3 connectivity input metanalysis files for drug tigecycline
toremifene 65 of 68
drug toremifene processed in 0.9
writing mit3 connectivity input metanalysis files for drug toremifene
trequinsin 66 of 68
drug trequinsin processed in 0.7
writing mit3 connectivity input metanalysis files for drug trequinsin
tyrphostin-A9 67 of 68
drug tyrphostin-A9 processed in 0.7
writing mit3 connectivity input metanalysis files for drug tyrphostin-A9
wortmannin 68 of 68
drug wortmannin processed in 0.7
writing mit3 connectivity input metanalysis files for drug wortmannin
time elapsed: 53.36206865310669

## Convert disease MITHrIL output into Connectivity Score input

In [4]:
print(MITH_OUT_DISEASE)

G:\My Drive\unict\unict 2024-25\netcos\MITHrIL\output\disease_signature_2025\

In [8]:
mith_file=MITH_OUT_DISEASE+DISEASE+'_mith3.perturbations.txt'
cs_data=mith_to_cs_in(mith_file)

In [10]:
cs_data

,gene_id,gene,Perturbation,p.value,adj.p.value
0,6197,"RPS6KA3, CLS, HU-3, ISPK-1, MAPKAPK1B, MRX19, ...",0.386794,1.000000,1.0
1,chebi:456216,ADP(3-),316.216558,0.819590,1.0
2,6196,"RPS6KA2, HU-2, MAPKAPK1C, RSK, RSK3, S6K-alpha...",0.384756,1.000000,1.0
3,chebi:30616,ATP(4-),56.183675,0.908046,1.0
4,5594,"MAPK1, ERK, ERK-2, ERK2, ERT1, MAPK2, NS13, P4...",1.009191,1.000000,1.0
...,...,...,...,...,...
388518,gl:G00711,(GlcA)1 (GlcNAc)2,0.337279,0.592704,1.0
388519,gl:G00526,(GlcA)2 (GlcNAc)2,1.862948,0.282359,1.0
390472,cpd:C00999,Ferrocytochrome b5,0.184327,1.000000,1.0
390474,123956252,RIPPLY2-CYB5R4,0.039842,1.000000,1.0
390479,cpd:C03691,CMP-N-glycoloylneuraminate,0.022236,0.971014,1.0

In [12]:
# write CS input
cs_input_name=DISEASE+'_mith3_signature.csv'
write_cs_input(cs_data, cs_input_name, CS_IN_DISEASE)

Connectivity score disease input file for MITHrIL perturbation data written at G:\My Drive\unict\unict 2024-25\netcos\connectivity_score\input\disease_signature_2025\LIHC\
file name: LIHC_mith3_signature.csv

# <div align="center"><b>Calculate connectivity score</b>

source code: connectivity_score.py

In [14]:
from cs_batch import run_connectivity_score_drugs_batch
from preprocessing_utils import get_drugs_list_from_path, get_chunk_indexes
from conf import DISEASE, CS_OUT, CS_IN_DRUG, CS_IN_DISEASE
print(DISEASE, cell_line, pert_time)
print(CS_IN_DRUG, CS_IN_DISEASE, CS_OUT)

LIHC HEPG2 6h
G:\My Drive\unict\unict 2024-25\netcos\connectivity_score\input\drug_signature_2025\HEPG2_6h\ G:\My Drive\unict\unict 2024-25\netcos\connectivity_score\input\disease_signature_2025\LIHC\ G:\My Drive\unict\unict 2024-25\netcos\connectivity_score\output\LIHC_2025_6h\

see validations/chembl/cs_run_chembl to run CS calculation

# Calculate IC50 Correlations
from validations/chembl/final_step_correlations_IC50

In [15]:
from validations.chembl.final_step_correlations_IC50_CS import load_drug_rankings, load_IC50
from scipy.stats import spearmanr

In [16]:
subset_metadata.rename(columns={'pert_iname':'drug'}, inplace=True)

C:\Users\los4\AppData\Local\Temp\ipykernel_32796\994324116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_metadata.rename(columns={'pert_iname':'drug'}, inplace=True)

In [19]:
data_of = {}  #no pert time, binchen LINCS1000 data
for cell_line in ['HT29']:
    print('-----------------------',cell_line)
    disease = diseases_of[cell_line]
    ic50 = load_IC50(disease, cell_line)
    BC_merged = df=pd.read_excel(DATA_DIR+'BinChen2017'+os.sep+'SD5.xlsx',\
                                 sheet_name=disease)
    print('pero bo questo excel e gia interseziaonato rges e ic50 se leggi il suo readme?')
    ic50_drugs=ic50['drug'].unique()
    print(len(ic50_drugs), 'drugs with IC50 value for cell line', cell_line)

    cs_out=CS_DIR+os.sep+'output'+os.sep+disease+'_2025_'+pert_time+os.sep
    print(cell_line, 'pert time',pert_time)
    
    drugs_to_run_mith_on=subset_metadata['drug'].unique()
    overlap_ic50_newlincs = set(drugs_to_run_mith_on).intersection(set(ic50_drugs))
    overlap_BC = overlap_ic50_newlincs.intersection(set(BC_merged.pert_iname))
    print('overlap between merged data with MCS vs merged data with sRGES from BinCHen2017', len(overlap_BC))
    print('n_IC50','n_MCS', 'n_MCSvIC50', 'n_sRGESvIC50','n_overlapSRGESvMCS')
    print(len(ic50_drugs), len(drugs_to_run_mith_on),len(overlap_ic50_newlincs),\
          BC_merged.shape[0],len(overlap_BC))

----------------------- HT29
pero bo questo excel e gia interseziaonato rges e ic50 se leggi il suo readme?
80 drugs with IC50 value for cell line HT29
HT29 pert time 6h
overlap between merged data with MCS vs merged data with sRGES from BinCHen2017 53
n_IC50 n_MCS n_MCSvIC50 n_sRGESvIC50 n_overlapSRGESvMCS
80 1845 53 93 53

C:\Users\los4\miniconda3\envs\drug_repurposing\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\los4\miniconda3\envs\drug_repurposing\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [20]:
overlap_BC

{'BRD-K00910650',
 'MG-132',
 'MLN-8054',
 'NPI-2358',
 'NVP-TAE684',
 'PD-173074',
 'PHA-665752',
 'SN-38',
 'amonafide',
 'amsacrine',
 'bosutinib',
 'camptothecin',
 'cladribine',
 'crizotinib',
 'cycloheximide',
 'cyclopamine',
 'dactinomycin',
 'daunorubicin',
 'digitoxin',
 'digoxin',
 'doxorubicin',
 'ellipticine',
 'emetine',
 'erlotinib',
 'gefitinib',
 'geldanamycin',
 'gemcitabine',
 'genistein',
 'hesperidin',
 'imatinib',
 'irinotecan',
 'lovastatin',
 'mepacrine',
 'mitomycin-c',
 'mitoxantrone',
 'neratinib',
 'niclosamide',
 'podophyllotoxin',
 'resveratrol',
 'saracatinib',
 'sinensetin',
 'sirolimus',
 'sorafenib',
 'sunitinib',
 'tamoxifen',
 'tanespimycin',
 'tangeritin',
 'tozasertib',
 'tretinoin',
 'triptolide',
 'vinblastine',
 'vinorelbine',
 'vorinostat'}

In [49]:
# OK ci siamo vicini ma non proprio.
# invece di fare questo coso, fai un dataset unico.

In [26]:
data_of = {} 
for cell_line in ['HT29']:
    print('-----------------------',cell_line)
    disease = diseases_of[cell_line]
    ic50 = load_IC50(disease, cell_line)
    BC_merged = df=pd.read_excel(DATA_DIR+'BinChen2017'+os.sep+'SD5.xlsx',\
                                 sheet_name=disease)
    print(ic50.shape, 'drugs with IC50 value for cell line', cell_line)

    for pert_time in ['6h', '24h']:
        cs_out=CS_DIR+os.sep+'output'+os.sep+disease+'_2025_'+pert_time+os.sep
        print(cell_line, 'pert time',pert_time)
        dr=load_drug_rankings(cs_out)
        merged = pd.merge(dr, ic50, on="drug", how="inner", suffixes=("_dr","_ic50"))

#
        
        merged = merged.dropna(subset=["connectivity_score","standard_value_median"]).copy()
        print('merged data on common drugs:', merged.shape)
        
        overlap_BC = set(merged.drug).intersection(set(BC_merged.pert_iname))
        print('overlap between merged data with MCS vs merged data with sRGES from BinCHen2017', len(overlap_BC))
        
        merged["log10_ic50"] = np.log10(merged["standard_value_median"])

        rho_linear, p_linear = spearmanr(merged["connectivity_score"], merged["standard_value_median"])
        rho_log, p_log = spearmanr(merged["connectivity_score"], merged["log10_ic50"])

        print('linear IC50: rho=', np.round(rho_linear,2),' pval =' ,np.round(p_linear, 2))
        print('log IC50: rho=', np.round(rho_log, 2),' pval =', np.round(p_log,2))
        
        BC_merged["log10_ic50"] = np.log10(BC_merged["standard_value"])
        
        BC_rho_linear, BC_p_linear = spearmanr(BC_merged["sRGES"], BC_merged["standard_value"])
        BC_rho_log, BC_p_log = spearmanr(BC_merged["sRGES"], BC_merged["log10_ic50"])
        
        print('linear IC50: rho=', np.round(rho_linear,2),' pval =' ,np.round(p_linear, 2))
        print('log IC50: rho=', np.round(rho_log, 2),' pval =', np.round(p_log,2))
        
        data_of[disease+'_'+pert_time] = [ic50.shape[0], dr.shape[0],\
                                          merged.shape[0],BC_merged.shape[0],\
                                        len(overlap_BC),rho_linear, p_linear,\
                                            rho_log, p_log, BC_rho_linear,\
                                            BC_p_linear, BC_rho_log, BC_p_log]
                
    
    data = pd.DataFrame(data_of).transpose()
    data.columns= ['n_IC50','n_MCS', 'n_MCSvIC50', \
                                            'n_sRGESvIC50','n_overlapSRGESvMCS',\
                                            'rho','p','rho_log','p_log',\
                                            'rho_sRGES', 'p_sRGES','rho_log_sRGES',\
                                                'p_log_sRGES']

----------------------- HT29
(392, 8) drugs with IC50 value for cell line HT29
HT29 pert time 6h

C:\Users\los4\miniconda3\envs\drug_repurposing\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\los4\miniconda3\envs\drug_repurposing\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

KeyError: ['connectivity_score']

In [14]:
data

,n_IC50,n_MCS,n_MCSvIC50,n_sRGESvIC50,n_overlapSRGESvMCS,rho,p,rho_log,p_log,rho_sRGES,p_sRGES,rho_log_sRGES,p_log_sRGES
COAD_6h,392.0,4765.0,343.0,93.0,65.0,-0.286463,6.679840e-08,-0.286463,6.679840e-08,0.30007,0.003475,0.30007,0.003475
COAD_24h,392.0,973.0,127.0,93.0,16.0,-0.767881,6.132857e-26,-0.767881,6.132857e-26,0.30007,0.003475,0.30007,0.003475